<a href="https://colab.research.google.com/github/pratyushhaihum/pratyushhaihum/blob/main/testing_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=1
b=2
print(a+b)

3


In [5]:
for i in range(1,21):
  if i%2==0:
    print(i)



2
4
6
8
10
12
14
16
18
20


In [6]:
import random

number = random.randint(1, 100)
guesses_left = 7

print("I'm thinking of a number between 1 and 100.")

while guesses_left > 0:
  try:
    guess = int(input("Take a guess: "))
  except ValueError:
    print("Invalid input. Please enter a number.")
    continue

  if guess < number:
    print("Too low!")
  elif guess > number:
    print("Too high!")
  else:
    print(f"You got it! The number was {number}")
    break

  guesses_left -= 1
  print(f"You have {guesses_left} guesses left.")

if guesses_left == 0:
  print(f"You ran out of guesses! The number was {number}")


I'm thinking of a number between 1 and 100.
Take a guess: 23
Too low!
You have 6 guesses left.
Take a guess: 78
You got it! The number was 78


In [7]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [8]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
arr1=np.array([2,5,9])
arr2=np.array([1,2,3])
print(arr1**arr2)

[  2  25 729]


In [14]:
import numpy as np
arr1=np.array([2,5,9])
arr2=np.array([1,2,3])
print(arr1*arr2)

[ 2 10 27]
